[package]
name = "sodium"
version = "0.1.0"
authors = ["Ticki"]
description = """
Sodium: A modern vi-like editor
"""

[dependencies]
orbclient = "0.3.32"

[features]
default = ["orbital"]
orbital = []
ansi = []
